---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "argocd-metrics-server.labels" . | nindent 4 }}
  name: {{ include "argocd-metrics-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "prometheus": {
        "applications": [
          {
            "name": "default",
            "default": true,
            "dashboards": [
              {{- .Values.prometheus.dashboards | nindent 14 }}
            ]
          }
        ],
        "provider":
        {
          "Name": "default",
          "default": true,
          "address": "http://{{ .Values.prometheus.service }}.{{ .Values.prometheus.namespace }}.svc.cluster.local:{{ .Values.prometheus.port }}{{ .Values.prometheus.path }}"
        }
      }
    }
