ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: umami.knell.it
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: umami.knell.it-tls
      hosts:
        - umami.knell.it

umami:
  disableLogin: "0"
  hostname: "umami.knell.it"

postgresql:
  enabled: true
  auth:
    database: umami
    password: umami1234
    username: umami
