{{- if .Values.taiga.backend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.taiga.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "taiga.backend.labels" . | nindent 4 }}
  name: {{ include "taiga.backend.serviceAccountName" . }}
{{- end }}
