---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "taiga.backend.labels" . | nindent 4 }}
  name: {{ include "taiga.backend.fullname" . }}
spec:
  type: {{ .Values.taiga.backend.service.type }}
  ports:
    - port: {{ .Values.taiga.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "taiga.backend.selectorLabels" . | nindent 4 }}
