---
{{- if or (eq .Values.rbac.mode "cluster-admin") (not .Values.rbac.namespaceLimits) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubenav.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  {{- if eq .Values.rbac.mode "cluster-admin" }}
  name: cluster-admin
  {{- else }}
  name: {{ include "kubenav.fullname" . }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubenav.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
