{{- if and (not (eq .Values.rbac.mode "cluster-admin")) (.Values.rbac.namespaceLimits) }}
{{- range .Values.rbac.namespaceLimits }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubenav.fullname" $ }}
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubenav.fullname" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubenav.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
