---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: {{ include "kubenav.serviceAccountName" . }}
  name: {{ include "kubenav.serviceAccountName" . }}
type: kubernetes.io/service-account-token
