apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shlink-backend.fullname" . }}
  labels:
    {{- include "shlink-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "shlink-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "shlink-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "shlink-backend.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
            # MariaDB Settings
            {{- if and .Values.mariadb.enabled (not .Values.mysql.enabled) (not .Values.postgresql.enabled) }}
            - name: DB_DRIVER
              value: mariadb
            - name: DB_HOST
              value: {{ include "mariadb.primary.fullname" .Subcharts.mariadb }}
            - name: DB_PORT
              value: {{ coalesce .Values.mariadb.primary.service.ports.mysql .Values.mariadb.primary.service.port | quote }}
            - name: DB_NAME
              value: {{ .Values.mariadb.auth.database | quote }}
            - name: DB_USER
              value: {{ .Values.mariadb.auth.username | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mariadb.secretName" .Subcharts.mariadb }}
                  key: mariadb-password
            {{- end }}
            # MySQL Settings
            {{- if and (not .Values.mariadb.enabled) .Values.mysql.enabled (not .Values.postgresql.enabled) }}
            - name: DB_DRIVER
              value: mysql
            - name: DB_HOST
              value: {{ include "mysql.primary.fullname" .Subcharts.mysql }}
            - name: DB_PORT
              value: {{ .Values.mysql.primary.service.ports.mysql | quote }}
            - name: DB_NAME
              value: {{ .Values.mysql.auth.database | quote }}
            - name: DB_USER
              value: {{ .Values.mysql.auth.username | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mysql.secretName" .Subcharts.mysql }}
                  key: mysql-password
            {{- end }}
            # PostgreSQL Settings
            {{- if and (not .Values.mariadb.enabled) (not .Values.mysql.enabled) .Values.postgresql.enabled }}
            - name: DB_DRIVER
              value: postgres
            - name: DB_HOST
              value: {{ include "postgresql.v1.primary.fullname" .Subcharts.postgresql }}
            - name: DB_PORT
              value: {{ include "postgresql.v1.service.port" .Subcharts.postgresql | quote }}
            - name: DB_NAME
              value: {{ include "postgresql.v1.database" .Subcharts.postgresql }}
            - name: DB_USER
              value: {{ include "postgresql.v1.username" .Subcharts.postgresql }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "postgresql.v1.secretName" .Subcharts.postgresql }}
                  key: {{ template "postgresql.v1.userPasswordKey" .Subcharts.postgresql }}
            {{- end }}
            {{- if .Values.externalDatabase.host }}
            - name: DB_DRIVER
              value: {{ .Values.externalDatabase.driver }}
            - name: DB_HOST
              value: {{ .Values.externalDatabase.host }}
            - name: DB_PORT
              value: {{ .Values.externalDatabase.port | quote }}
            - name: DB_NAME
              value: {{ .Values.externalDatabase.database }}
            - name: DB_USER
              value: {{ .Values.externalDatabase.username }}
            {{- if .Values.externalDatabase.externalSecretName }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDatabase.externalSecretName }}
                  key: {{ .Values.externalDatabase.externalSecretKey }}
            {{- else }}
            - name: DB_PASSWORD
              value: {{ .Values.externalDatabase.password }}
            {{- end }}
            {{- end }}
            # RabbitMQ Settings
            {{- if .Values.rabbitmq.enabled }}
            - name: RABBITMQ_ENABLED
              value: "true"
            - name: RABBITMQ_HOST
              value: {{ include "common.names.fullname" .Subcharts.rabbitmq | quote }}
            - name: RABBITMQ_PORT
              {{- if or (.Values.rabbitmq.service.portEnabled) (not .Values.rabbitmq.auth.tls.enabled) }}
              value: {{ .Values.rabbitmq.service.ports.amqp | quote }}
              {{- else if .Values.rabbitmq.auth.tls.enabled }}
              value: {{ .Values.rabbitmq.service.ports.amqpTls | quote }}
              {{- end }}
            - name: RABBITMQ_USER
              value: {{ .Values.rabbitmq.auth.username | quote }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "rabbitmq.secretPasswordName" .Subcharts.rabbitmq }}
                  key: rabbitmq-password
            {{- end }}
            # Redis Settings
            {{- if .Values.redis.enabled }}
            - name: REDIS_SERVERS
              value: {{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}:{{ .Values.redis.master.service.ports.redis }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /rest/health
              port: http
          readinessProbe:
            httpGet:
              path: /rest/health
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
