{{- if (not .Values.taiga.common.config.integrations.githubImporter.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiga.common.githubImporter.secretName" . }}
data:
  client-secret: {{ .Values.taiga.common.config.integrations.githubImporter.clientSecret | b64enc }}
{{- end }}
