# Explanation: Add the label 'ci-cd' to a PR if any file within the '.github' folder is changed
ci-cd:
- changed-files:
  - any-glob-to-any-file: '.github/config/*'
  - any-glob-to-any-file: '.github/workflows/*'

# charts
ansible-semaphore:
- changed-files:
  - any-glob-to-any-file: 'charts/ansible-semaphore/*'
argocd-metrics-server:
- changed-files:
  - any-glob-to-any-file: 'charts/argocd-metrics-server/*'
audiobookshelf:
- changed-files:
  - any-glob-to-any-file: charts/audiobookshelf/*
baserow:
- changed-files:
  - any-glob-to-any-file: 'charts/baserow/*'
bluespice:
- changed-files:
  - any-glob-to-any-file: charts/bluespice/*
cluster-api-visualizer:
- changed-files:
  - any-glob-to-any-file: 'charts/cluster-api-visualizer/*'
countly:
- changed-files:
  - any-glob-to-any-file: charts/countly/*
cusdis:
- changed-files:
  - any-glob-to-any-file: charts/cusdis/*
dasherr:
- changed-files:
  - any-glob-to-any-file: charts/dasherr/*
dns-exporter:
- changed-files:
  - any-glob-to-any-file: charts/dns-exporter/*
dnsbl-exporter:
- changed-files:
  - any-glob-to-any-file: charts/dnsbl-exporter/*
docker_stats_exporter:
- changed-files:
  - any-glob-to-any-file: charts/docker_stats_exporter/*
ecs-exporter:
- changed-files:
  - any-glob-to-any-file: charts/ecs-exporter/*
etcd-defrag:
- changed-files:
  - any-glob-to-any-file: charts/etcd-defrag/*
fathom:
- changed-files:
  - any-glob-to-any-file: charts/fathom/*
freshrss:
- changed-files:
  - any-glob-to-any-file: charts/freshrss/*
github-exporter:
- changed-files:
  - any-glob-to-any-file: 'charts/github-exporter/*'
glances:
- changed-files:
  - any-glob-to-any-file: charts/glances/*
goaccess:
- changed-files:
  - any-glob-to-any-file: charts/goaccess/*
goldpinger:
- changed-files:
  - any-glob-to-any-file: charts/goldpinger/*
greenbone-ce:
- changed-files:
  - any-glob-to-any-file: charts/greenbone-ce/*
headwind-mdm:
- changed-files:
  - any-glob-to-any-file: charts/headwind-mdm/*
ipmi-exporter:
- changed-files:
  - any-glob-to-any-file: charts/ipmi-exporter/*
ipsec-exporter:
- changed-files:
  - any-glob-to-any-file: charts/ipsec-exporter/*
isso:
- changed-files:
  - any-glob-to-any-file: charts/isso/*
kateyes:
- changed-files:
  - any-glob-to-any-file: charts/kateyes/*
kirby:
- changed-files:
  - any-glob-to-any-file: charts/kirby/*
kubedoom:
- changed-files:
  - any-glob-to-any-file: charts/kubedoom/*
kubenav:
- changed-files:
  - any-glob-to-any-file: charts/kubenav/*
kube-ops-view:
- changed-files:
  - any-glob-to-any-file: charts/kube-ops-view/*
kubevirt-manager:
- changed-files:
  - any-glob-to-any-file: charts/kubevirt-manager/*
kutt:
- changed-files:
  - any-glob-to-any-file: charts/kutt/*
lxd-dashboard:
- changed-files:
  - any-glob-to-any-file: charts/lxd-dashboard/*
mailcow-exporter:
- changed-files:
  - any-glob-to-any-file: charts/mailcow-exporter/*
maildev:
- changed-files:
  - any-glob-to-any-file: charts/maildev/*
node-access:
- changed-files:
  - any-glob-to-any-file: charts/node-access/*
netcupscp-exporter:
- changed-files:
  - any-glob-to-any-file: charts/netcupscp-exporter/*
nextcloud-exporter:
- changed-files:
  - any-glob-to-any-file: charts/nextcloud-exporter/*
passbolt-ha:
- changed-files:
  - any-glob-to-any-file: charts/passbolt-ha/*
polr:
- changed-files:
  - any-glob-to-any-file: charts/polr/*
popeye:
- changed-files:
  - any-glob-to-any-file: charts/popeye/*
postal:
- changed-files:
  - any-glob-to-any-file: charts/postal/*
priority-classes:
- changed-files:
  - any-glob-to-any-file: charts/priority-classes/*
promlens:
- changed-files:
  - any-glob-to-any-file: charts/promlens/*
prometheus-pve-exporter:
- changed-files:
  - any-glob-to-any-file: charts/prometheus-pve-exporter/*
proxysql:
- changed-files:
  - any-glob-to-any-file: charts/proxysql/*
proxyweb:
- changed-files:
  - any-glob-to-any-file: charts/proxyweb/*
shlink-backend:
- changed-files:
  - any-glob-to-any-file: charts/shlink-backend/*
shlink-web:
- changed-files:
  - any-glob-to-any-file: charts/shlink-web/*
skooner:
- changed-files:
  - any-glob-to-any-file: charts/skooner/*
sloop:
- changed-files:
  - any-glob-to-any-file: charts/sloop/*
squest:
- changed-files:
  - any-glob-to-any-file: charts/squest/*
standardnotes:
- changed-files:
  - any-glob-to-any-file: charts/standardnotes/*
syncserver:
- changed-files:
  - any-glob-to-any-file: charts/syncserver/*
syncstorage-rs:
- changed-files:
  - any-glob-to-any-file: charts/syncstorage-rs/*
talkyard:
- changed-files:
  - any-glob-to-any-file: charts/talkyard/*
tenant-namespace:
- changed-files:
  - any-glob-to-any-file: charts/tenant-namespace/*
typo3:
- changed-files:
  - any-glob-to-any-file: charts/typo3/*
umami:
- changed-files:
  - any-glob-to-any-file: charts/umami/*
