---
# https://github.com/23andMe/Yamale#schema
annotations: include('annotation_entries', required=True, strict=False)
apiVersion: str(required=True)
appVersion: any(str(), num(), required=False)
condition: str(required=False)
dependencies: list(include('dependency'), required=False)
deprecated: bool(required=False)
description: str(required=False)
engine: str(required=False)
home: str(required=True)
icon: str(required=False)
keywords: list(str(), required=False)
kubeVersion: str(required=False)
maintainers: list(include('maintainer'), required=True)
name: str(required=True)
sources: list(str(), required=False)
tags: str(required=False)
type: str(required=False)
version: str(required=True)
---
dependency:
  alias: str(required=False)
  condition: str(required=False)
  import-values: list(str(), required=False)
  name: str(required=True)
  repository: str(required=False)
  tags: list(str(), required=False)
  version: str(required=True)
---
maintainer:
  name: str(required=True)
  email: str(required=True)
  url: str(required=False)
---
annotation_entries:
  artifacthub.io/alternativeName: str(required=False)
  artifacthub.io/category: enum("ai-machine-learning", "database", "integration-delivery", "monitoring-logging", "networking", "security", "storage", "streaming-messaging", required=False)
  artifacthub.io/changes: |
    regex("^- kind: .+\\n  description: .+", multiline=True)
  artifacthub.io/containsSecurityUpdates: enum("true", "false", required=False)
  artifacthub.io/crds: str(required=False)
  artifacthub.io/crdsExamples: str(required=False)
  artifacthub.io/images: str(required=False)
  artifacthub.io/license: str(required=False)
  artifacthub.io/links: str(required=False)
  artifacthub.io/maintainers: str(required=False)
  artifacthub.io/operator: enum("true", "false", required=False)
  artifacthub.io/operatorCapabilities: str(required=False)
  artifacthub.io/prerelease: enum("true", "false", required=False)
  artifacthub.io/recommendations: str(required=False)
  artifacthub.io/screenshots: str(required=False)
  artifacthub.io/signKey: str(required=False)
