---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "goldpinger.labels" . | nindent 4 }}
  name: {{ include "goldpinger.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.goldpinger.port | int }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "goldpinger.selectorLabels" . | nindent 4 }}
