# -- Enable/disable individual CRDs. Keys match each CRD's plural name
# (`spec.names.plural`).
crds:
  # -- Installs the BackendTLSPolicy CRD.
  backendtlspolicies: true
  # -- Installs the GatewayClass CRD.
  gatewayclasses: true
  # -- Installs the Gateway CRD.
  gateways: true
  # -- Installs the GRPCRoute CRD.
  grpcroutes: true
  # -- Installs the HTTPRoute CRD.
  httproutes: true
  # -- Installs the ListenerSet CRD.
  listenersets: true
  # -- Installs the ReferenceGrant CRD.
  referencegrants: true
  # -- Installs the TCPRoute CRD.
  tcproutes: true
  # -- Installs the TLSRoute CRD.
  tlsroutes: true
  # -- Installs the UDPRoute CRD.
  udproutes: true
  # -- Installs the XBackendTrafficPolicy CRD.
  xbackendtrafficpolicies: true
  # -- Installs the XListenerSet CRD.
  xlistenersets: true
  # -- Installs the XMesh CRD.
  xmeshes: true
