{{- if not .Values.argocd.auth.existingSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-for-argocd.auth.secretName" . }}
data:
  {{- (include "mcp-for-argocd.auth.apiToken.secretKey" .) | nindent 2 }}: {{ .Values.argocd.auth.apiToken | b64enc | quote }}
{{- end }}
{{- if and (not .Values.auth.allowUnauthenticated) (not .Values.auth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-for-argocd.inboundAuth.secretName" . }}
data:
  {{- (include "mcp-for-argocd.inboundAuth.secretKey" .) | nindent 2 }}: {{ .Values.auth.token | b64enc | quote }}
{{- end }}
