{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netcupscp-exporter.auth.secretName" . }}
data:
  SCP_REFRESHTOKEN: {{ .Values.auth.refreshToken |b64enc }}
{{- end }}
