ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  className: nginx
  hosts:
    - host: capi-visualizer.167.235.106.217.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: capi-visualizer.167.235.106.217.nip.io-tls
      hosts:
        - capi-visualizer.167.235.106.217.nip.io
