{{- if and .Values.proxysql.secret.enabled (not .Values.proxysql.secret.existingSecret) (not .Values.proxysql.configmap) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  proxysql.cnf: |
    {{- include "proxysql.config" . | nindent 4 }}
{{- end }}
