{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.metrics.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
  name: {{ include "proxysql.fullname" . }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      scrapeTimeout: 10s
      port: metrics
  jobLabel: ""
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "proxysql.selectorLabels" . | nindent 6 }}
{{- end }}
