apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baserow.backend.fullname" . }}
data:
  # Baserow Backend Settings
  BASEROW_ACCESS_TOKEN_LIFETIME_MINUTES: {{ .Values.backend.config.tokens.accessTokenLifetimeMinutes | quote }}
  BASEROW_AIRTABLE_IMPORT_SOFT_TIME_LIMIT: {{ .Values.backend.config.airtableImportSoftTimeLimit | quote }}
  {{- if .Values.backend.config.amountOfGunicornWorkers }}
  BASEROW_AMOUNT_OF_GUNICORN_WORKERS: {{ .Values.backend.config.amountOfGunicornWorkers | quote }}
  {{- end }}
  BASEROW_BACKEND_DATABASE_LOG_LEVEL: {{ .Values.backend.config.logging.databaseLogLevel | quote }}
  BASEROW_BACKEND_DEBUG: {{ .Values.backend.config.logging.backendDebug | quote }}
  BASEROW_BACKEND_LOG_LEVEL: {{ .Values.backend.config.logging.backendLogLevel | quote }}
  {{- if and (.Values.backend.ingress.enabled) (.Values.backend.ingress.hostname) }}
  BASEROW_EXTRA_ALLOWED_HOSTS: {{ .Values.backend.ingress.hostname | quote }}
  {{- end }}
  BASEROW_FILE_UPLOAD_SIZE_LIMIT_MB: {{ .Values.backend.config.fileUploadSizeLimit | quote }}
  BASEROW_REFRESH_TOKEN_LIFETIME_HOURS: {{ .Values.backend.config.tokens.refreshTokenLifetimeHours | quote }}
  BASEROW_ROW_PAGE_SIZE_LIMIT: {{ .Values.backend.config.rowPageSizeLimit | quote }}
  BASEROW_SNAPSHOT_EXPIRATION_TIME_DAYS: {{ .Values.backend.config.snapshotExpirationTimeDays | quote }}
  BASEROW_SYNC_TEMPLATES_TIME_LIMIT: {{ .Values.backend.config.syncTemplatesTimeLimit | quote }}
  BASEROW_TRIGGER_SYNC_TEMPLATES_AFTER_MIGRATION: {{ .Values.backend.config.triggerSyncTemplatesAfterMigration | quote }}
  BATCH_ROWS_SIZE_LIMIT: {{ .Values.backend.config.batchRowsSizeLimit | quote }}
  {{- if .Values.backend.config.dontUpdateFormulasAfterMigration }}
  DONT_UPDATE_FORMULAS_AFTER_MIGRATION: {{ .Values.backend.config.dontUpdateFormulasAfterMigration | quote }}
  {{- end }}
  {{- if .Values.backend.config.initialTableDataLimit }}
  INITIAL_TABLE_DATA_LIMIT: {{ .Values.backend.config.initialTableDataLimit | quote }}
  {{- end }}
  MIGRATE_ON_STARTUP: {{ .Values.backend.config.migrateOnStartup | quote }}
  POSTGRES_STARTUP_CHECK_ATTEMPTS: {{ .Values.backend.config.postgresStartupCheckAttempts | quote }}
  # Baserow Backend Misc Configuration
  {{- if .Values.backend.config.additionalApps }}
  ADDITIONAL_APPS: {{ .Values.backend.config.additionalApps | quote }}
  {{- end }}
  {{- if .Values.backend.config.disableModelCache }}
  BASEROW_DISABLE_MODEL_CACHE: {{ .Values.backend.config.disableModelCache | quote }}
  {{- end }}
  {{- if .Values.backend.config.enableSecureProxySslHeader }}
  BASEROW_ENABLE_SECURE_PROXY_SSL_HEADER: {{ .Values.backend.config.enableSecureProxySslHeader | quote }}
  {{- end }}
  BASEROW_INITIAL_CREATE_SYNC_TABLE_DATA_LIMIT: {{ .Values.backend.config.initialCreateSyncTableDataLimit | quote }}
  BASEROW_JOB_CLEANUP_INTERVAL_MINUTES: {{ .Values.backend.config.jobs.cleanupIntervalMinutes | quote }}
  BASEROW_JOB_EXPIRATION_TIME_LIMIT: {{ .Values.backend.config.jobs.expirationTimeLimit | quote }}
  BASEROW_JOB_SOFT_TIME_LIMIT: {{ .Values.backend.config.jobs.softTimeLimit | quote }}
  BASEROW_MAX_FILE_IMPORT_ERROR_COUNT: {{ .Values.backend.config.maxFileImportErrorCount | quote }}
  BASEROW_MAX_ROW_REPORT_ERROR_COUNT: {{ .Values.backend.config.maxRowReportErrorCount | quote }}
  {{- if .Values.backend.config.waitInsteadOf409ConflictError }}
  BASEROW_WAIT_INSTEAD_OF_409_CONFLICT_ERROR: {{ .Values.backend.config.waitInsteadOf409ConflictError | quote }}
  {{- end }}
  {{- if .Values.backend.config.disableAnonymousPublicViewWsConnections }}
  DISABLE_ANONYMOUS_PUBLIC_VIEW_WS_CONNECTIONS: {{ .Values.backend.config.disableAnonymousPublicViewWsConnections | quote }}
  {{- end }}
  {{- if .Values.backend.config.hoursUntilTrashPermanentlyDeleted }}
  HOURS_UNTIL_TRASH_PERMANENTLY_DELETED: {{ .Values.backend.config.hoursUntilTrashPermanentlyDeleted | quote }}
  {{- end }}
  MINUTES_UNTIL_ACTION_CLEANED_UP: {{ .Values.backend.config.minutesUntilActionCleanedUp | quote }}
  # Baserow Celery Settings
  BASEROW_AMOUNT_OF_WORKERS: {{ .Values.backend.config.celery.amountOfWorkers | quote }}
  BASEROW_CELERY_BEAT_DEBUG_LEVEL: {{ .Values.backend.config.celery.beatDebugLevel | quote }}
  BASEROW_CELERY_BEAT_STARTUP_DELAY: {{ .Values.backend.config.celery.beatStartupDelay | quote }}
  BASEROW_RUN_MINIMAL: {{ .Values.backend.config.celery.runMinimal | quote }}
  # Baserow Email Settings
  {{- if .Values.backend.config.email.smtp }}
  EMAIL_SMTP: {{ .Values.backend.config.email.smtp | quote }}
  {{- if .Values.backend.config.email.smtpUseTls }}
  EMAIL_SMTP_USE_TLS: {{ .Values.backend.config.email.smtpUseTls | quote }}
  {{- end }}
  {{- if .Values.backend.config.email.smtpHost }}
  EMAIL_SMTP_HOST: {{ .Values.backend.config.email.smtpHost | quote }}
  {{- end }}
  {{- if .Values.backend.config.email.smtpPort }}
  EMAIL_SMTP_PORT: {{ .Values.backend.config.email.smtpPort | quote }}
  {{- end }}
  {{- if .Values.backend.config.email.smtpUser }}
  EMAIL_SMTP_USER: {{ .Values.backend.config.email.smtpUser | quote }}
  {{- end }}
  {{- if .Values.backend.config.email.fromEmail }}
  FROM_EMAIL: {{ .Values.backend.config.email.fromEmail | quote }}
  {{- end }}
  {{- end }}
  # Baserow File Upload Settings
  AWS_STORAGE_BUCKET_NAME: {{ .Values.backend.config.aws.bucketName | quote }}
  {{- if .Values.backend.config.aws.s3CustomDomain }}
  AWS_S3_CUSTOM_DOMAIN: {{ .Values.backend.config.aws.s3CustomDomain | quote }}
  {{- end }}
  {{- if .Values.backend.config.aws.s3EndpointUrl }}
  AWS_S3_ENDPOINT_URL: {{ .Values.backend.config.aws.s3EndpointUrl | quote }}
  {{- end }}
  {{- if .Values.backend.config.aws.s3RegionName }}
  AWS_S3_REGION_NAME: {{ .Values.backend.config.aws.s3RegionName | quote }}
  {{- end }}
  MEDIA_ROOT: {{ .Values.backend.config.media.root | quote }}
  MEDIA_URL: {{ .Values.backend.config.media.url | quote }}
  # Baserow Webhook Settings
  {{- if .Values.backend.config.webhook.allowPrivateAddress }}
  BASEROW_WEBHOOKS_ALLOW_PRIVATE_ADDRESS: {{ .Values.backend.config.webhook.allowPrivateAddress | quote }}
  {{- end }}
  {{- if .Values.backend.config.webhook.ipBlacklist }}
  BASEROW_WEBHOOKS_IP_BLACKLIST: {{ .Values.backend.config.webhook.ipBlacklist | quote }}
  {{- end }}
  {{- if .Values.backend.config.webhook.ipWhitelist }}
  BASEROW_WEBHOOKS_IP_WHITELIST: {{ .Values.backend.config.webhook.ipWhitelist | quote }}
  {{- end }}
  BASEROW_WEBHOOKS_MAX_CALL_LOG_ENTRIES: {{ .Values.backend.config.webhook.maxCallLogEntries | quote }}
  BASEROW_WEBHOOKS_MAX_CONSECUTIVE_TRIGGER_FAILURES: {{ .Values.backend.config.webhook.maxConsecutiveTriggerFailures | quote }}
  BASEROW_WEBHOOKS_MAX_PER_TABLE: {{ .Values.backend.config.webhook.maxPerTable | quote }}
  BASEROW_WEBHOOKS_MAX_RETRIES_PER_CALL: {{ .Values.backend.config.webhook.maxRetriesPerCall | quote }}
  BASEROW_WEBHOOKS_REQUEST_TIMEOUT_SECONDS: {{ .Values.backend.config.webhook.requestTimeoutSeconds | quote }}
  BASEROW_WEBHOOKS_URL_CHECK_TIMEOUT_SECS: {{ .Values.backend.config.webhook.urlCheckTimeoutSecs | quote }}
  {{- if .Values.backend.config.webhook.urlRegexBlacklist }}
  BASEROW_WEBHOOKS_URL_REGEX_BLACKLIST: {{ .Values.backend.config.webhook.urlRegexBlacklist | quote }}
  {{- end }}
  # Database Settings
  DATABASE_HOST: {{ include "baserow.postgresql.hostname" . | quote }}
  DATABASE_PORT: {{ include "baserow.postgresql.port" . | quote }}
  DATABASE_NAME: {{ include "baserow.postgresql.database" . | quote }}
  DATABASE_USER: {{ include "baserow.postgresql.username" . | quote }}
  # Redis Settings
  REDIS_HOST: {{ include "baserow.redis.hostname" . | quote }}
  REDIS_PORT: {{ include "baserow.redis.port" . | quote }}
