---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "audiobookshelf.labels" . | nindent 4 }}
  name: {{ include "audiobookshelf.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port | int }}
      targetPort: http
  selector:
    {{- include "audiobookshelf.selectorLabels" . | nindent 4 }}
