{{- if .Values.taiga.common.ingress.enabled -}}
{{- $fullName := include "taiga.fullname" . -}}
{{- $backendSvcName := include "taiga.backend.fullname" . -}}
{{- $backendSvcPort := .Values.taiga.backend.service.port -}}
{{- $eventsSvcName := include "taiga.events.fullname" . -}}
{{- $eventsSvcPort := .Values.taiga.events.service.port -}}
{{- $frontendSvcName := include "taiga.frontend.fullname" . -}}
{{- $frontendSvcPort := .Values.taiga.frontend.service.port -}}
{{- if and .Values.taiga.common.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.taiga.common.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.taiga.common.ingress.annotations "kubernetes.io/ingress.class" .Values.taiga.common.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  {{- with .Values.taiga.common.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
  name: {{ $fullName }}
spec:
  {{- if and .Values.taiga.common.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.taiga.common.ingress.className }}
  {{- end }}
  {{- if .Values.taiga.common.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.taiga.common.ingress.hostname | quote }}
      secretName: {{ .Values.taiga.common.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.taiga.common.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            {{- if and .Values.taiga.common.ingress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .Values.taiga.common.ingress.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $frontendSvcName }}
                port:
                  number: {{ $frontendSvcPort }}
              {{- else }}
              serviceName: {{ $frontendSvcName }}
              servicePort: {{ $frontendSvcPort }}
              {{- end }}
          - path: /admin
            {{- if and .Values.taiga.common.ingress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .Values.taiga.common.ingress.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $backendSvcName }}
                port:
                  number: {{ $frontendSvcPort }}
              {{- else }}
              serviceName: {{ $backendSvcName }}
              servicePort: {{ $backendSvcPort }}
              {{- end }}
          - path: /api
            {{- if and .Values.taiga.common.ingress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .Values.taiga.common.ingress.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $backendSvcName }}
                port:
                  number: {{ $frontendSvcPort }}
              {{- else }}
              serviceName: {{ $backendSvcName }}
              servicePort: {{ $backendSvcPort }}
              {{- end }}
          - path: /events
            {{- if and .Values.taiga.common.ingress.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .Values.taiga.common.ingress.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $eventsSvcName }}
                port:
                  number: {{ $eventsSvcPort }}
              {{- else }}
              serviceName: {{ $eventsSvcName }}
              servicePort: {{ $eventsSvcPort }}
              {{- end }}
{{- end }}
