{{- if and (not .Values.postgresql.enabled) (not .Values.externalPostgresql.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "baserow.postgresql.secretName" . }}
data:
  {{- include "baserow.postgresql.userPasswordKey" . | nindent 2 }}: {{ .Values.externalPostgresql.auth.password | b64enc }}
  {{- if .Values.externalPostgresql.auth.userUsernameKey }}
  {{- include "baserow.postgresql.userUsernameKey" . | nindent 2 }}: {{ .Values.externalPostgresql.auth.username | b64enc }}
  {{- end }}
{{- end }}
