apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kutt.fullname" . }}
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "kutt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kutt.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kutt.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.kutt.admin.emails }}
            # Admin Settings
            - name: ADMIN_EMAILS
              value: {{ .Values.kutt.admin.emails | quote }}
            {{- end }}
            # Configuration Settings
            - name: DISALLOW_ANONYMOUS_LINKS
              value: {{ .Values.kutt.config.disallowAnonymousLinks | quote }}
            - name: DISALLOW_REGISTRATION
              value: {{ .Values.kutt.config.disallowRegistration | quote }}
            - name: ENABLE_RATE_LIMIT
              value: {{ .Values.kutt.config.enableRateLimit | quote }}
            - name: LINK_CUSTOM_ALPHABET
              value: {{ .Values.kutt.config.linkCustomAlphabet | quote }}
            - name: LINK_LENGTH
              value: {{ .Values.kutt.config.linkLength | quote }}
            - name: SITE_NAME
              value: {{ .Values.kutt.config.siteName | quote }}
            # Domain Settings
            - name: CUSTOM_DOMAIN_USE_HTTPS
              value: {{ .Values.kutt.domain.customDomainUseHttps | quote }}
            {{- if or (.Values.kutt.domain.defaultDomain) (and .Values.kutt.domain.useFirstIngressHost .Values.ingress.enabled (index .Values.ingress.hosts 0).host) }}
            - name: DEFAULT_DOMAIN
              {{- if and .Values.kutt.domain.useFirstIngressHost .Values.ingress.enabled (index .Values.ingress.hosts 0).host }}
              value: {{ (index .Values.ingress.hosts 0).host | quote }}
              {{- else }}
              value: {{ .Values.kutt.domain.defaultDomain | quote }}
              {{- end }}
            {{- end }}
            # Mail Settings
            {{- if .Values.kutt.mail.contactEmail }}
            - name: CONTACT_EMAIL
              value: {{ .Values.kutt.mail.contactEmail | quote }}
            {{- end }}
            {{- if .Values.kutt.mail.enabled }}
            - name: MAIL_ENABLED
              value: {{ .Values.kutt.mail.enabled | quote }}
            {{- end }}
            {{- if .Values.kutt.mail.host }}
            - name: MAIL_HOST
              value: {{ .Values.kutt.mail.host | quote }}
            {{- end }}
            {{- if .Values.kutt.mail.port }}
            - name: MAIL_PORT
              value: {{ .Values.kutt.mail.port | quote }}
            {{- end }}
            {{- if .Values.kutt.mail.from }}
            - name: MAIL_FROM
              value: {{ .Values.kutt.mail.from | quote }}
            {{- end }}
            - name: MAIL_SECURE
              value: {{ .Values.kutt.mail.secure | quote }}
            {{- if .Values.kutt.mail.username }}
            - name: MAIL_USER
              value: {{ .Values.kutt.mail.username | quote }}
            {{- end }}
            - name: MAIL_PASSWORD
              {{- if .Values.kutt.mail.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kutt.mail.existingSecret }}
                  key: MAIL_PASSWORD
              {{- else }}
              value: {{ .Values.kutt.mail.password | quote }}
              {{- end }}
            {{- if .Values.kutt.mail.reportEmail }}
            - name: REPORT_EMAIL
              value: {{ .Values.kutt.mail.reportEmail | quote }}
            {{- end }}
            # JWT Settings
            - name: JWT_SECRET
              {{- if .Values.kutt.jwt.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kutt.jwt.existingSecret }}
                  key: JWT_SECRET
              {{- else }}
              value: {{ .Values.kutt.jwt.key }}
              {{- end }}
            # Database Settings
            - name: DB_CLIENT
              value: {{ include "kutt.postgresql.client" . | quote }}
            - name: DB_HOST
              value: {{ include "kutt.postgresql.hostname" . | quote }}
            - name: DB_PORT
              value: {{ include "kutt.postgresql.port" . | quote }}
            - name: DB_NAME
              value: {{ include "kutt.postgresql.database" . | quote }}
            - name: DB_USER
              value: {{ include "kutt.postgresql.username" . | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kutt.postgresql.secretName" . | quote }}
                  key: {{ include "kutt.postgresql.userPasswordKey" . | quote }}
            - name: DB_POOL_MAX
              value: {{ .Values.kutt.database.pool.max | quote }}
            - name: DB_POOL_MIN
              value: {{ .Values.kutt.database.pool.min | quote }}
            - name: DB_SSL
              value: "false"
            # Redis Settings
            - name: REDIS_ENABLED
              value: {{ .Values.redis.enabled | quote }}
            - name: REDIS_HOST
              value: {{ include "kutt.redis.hostname" . | quote }}
            - name: REDIS_PORT
              value: {{ include "kutt.redis.port" . | quote }}
            {{- if eq (include "kutt.redis.auth.enabled" .) "true" }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kutt.redis.secretName" . | quote }}
                  key: {{ include "kutt.redis.userPasswordKey" . | quote }}
            {{- end -}}
            {{- range .Values.extraEnv }}
            {{- if and (.name) (.value) }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v2/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/v2/health
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
