---
syncserver:
  config:
    secret: "bla"
  extraEnv:
    - name: foo
      value: bar
  persistence:
    enabled: true
    existingClaim: syncserver
    resources:
      limits:
        storage: 20Gi
      requests:
        storage: 10Gi
