apiVersion: v2
name: gateway-api-crds
description: Kubernetes Gateway API CustomResourceDefinitions (standard and experimental channel)
type: application
version: 1.2.0
appVersion: "v1.5.1"
home: https://github.com/christianhuth/helm-charts
icon: https://raw.githubusercontent.com/christianhuth/helm-charts/refs/heads/main/charts/gateway-api-crds/icon.svg
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://github.com/kubernetes-sigs/gateway-api
dependencies:
  - name: standard
    version: 1.2.0
    condition: standard.enabled
  - name: experimental
    version: 1.2.0
    condition: experimental.enabled
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Gateway API CRDs to v1.5.1
  artifacthub.io/links: |
    - name: support
      url: https://github.com/christianhuth/helm-charts/issues
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
