# -- Provide a name in place of `baserow`
nameOverride: ""

# -- String to fully override `"baserow.fullname"`
fullnameOverride: ""

api:

  image:
    # -- image registry
    registry: docker.io
    # -- image repository
    repository: countly/api
    # -- image pull policy
    pullPolicy: Always
    # -- Overrides the image tag
    tag: "25.05.4"

  # -- If defined, uses a Secret to pull an image from a private Docker registry or repository.
  imagePullSecrets: []

  # -- Annotations to be added to the frontend pods
  podAnnotations: {}

  # -- pod-level security context
  podSecurityContext: {}

  # -- Pod priority class name
  priorityClassName: ""

  # -- Number of replicas
  replicaCount: 1

  # -- The number of old ReplicaSets to retain
  revisionHistoryLimit: 10

  # -- Resource limits and requests for the controller pods.
  # @default -- see [values.yaml](./values.yaml)
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 400Mi

  # -- container-level security context
  securityContext: {}

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  service:
    # -- Kubernetes service type
    type: ClusterIP
    # -- Kubernetes port where service is exposed
    port: 3000

  autoscaling:
    # -- Enable Horizontal POD autoscaling
    enabled: false
    # -- Minimum number of replicas
    minReplicas: 1
    # -- Maximum number of replicas
    maxReplicas: 100
    # -- Target CPU utilization percentage
    targetCPUUtilizationPercentage: 80
    # -- Target Memory utilization percentage
    targetMemoryUtilizationPercentage: 80

  livenessProbe:
    # -- Failure threshold for livenessProbe
    failureThreshold: 6
    # -- Initial delay seconds for livenessProbe
    initialDelaySeconds: 60
    # -- Period seconds for livenessProbe
    periodSeconds: 30
    # -- Success threshold for livenessProbe
    successThreshold: 1
    # -- Timeout in seconds for livenessProbe
    timeoutSeconds: 2

  readinessProbe:
    # -- Failure threshold for readinessProbe
    failureThreshold: 6
    # -- Initial delay seconds for readinessProbe
    initialDelaySeconds: 60
    # -- Period seconds for readinessProbe
    periodSeconds: 30
    # -- Success threshold for readinessProbe
    successThreshold: 1
    # -- Timeout in seconds for readinessProbe
    timeoutSeconds: 2

  # -- Node labels for pod assignment
  nodeSelector: {}

  # -- Toleration labels for pod assignment
  tolerations: []

  # -- Affinity settings for pod assignment
  affinity: {}

  # -- Additional labels to add to the pod
  selectorLabels: {}

  # -- additional environment variables to be added to the api pods
  extraEnv: []

frontend:

  image:
    # -- image registry
    registry: docker.io
    # -- image repository
    repository: countly/frontend
    # -- image pull policy
    pullPolicy: Always
    # -- Overrides the image tag
    tag: "24.10.8"

  # -- If defined, uses a Secret to pull an image from a private Docker registry or repository.
  imagePullSecrets: []

  # -- Annotations to be added to the frontend pods
  podAnnotations: {}

  # -- pod-level security context
  podSecurityContext: {}

  # -- Pod priority class name
  priorityClassName: ""

  # -- Number of replicas
  replicaCount: 1

  # -- The number of old ReplicaSets to retain
  revisionHistoryLimit: 10

  # -- Resource limits and requests for the controller pods.
  # @default -- see [values.yaml](./values.yaml)
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi

  # -- container-level security context
  securityContext: {}

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  service:
    # -- Kubernetes service type
    type: ClusterIP
    # -- Kubernetes port where service is exposed
    port: 3000

  autoscaling:
    # -- Enable Horizontal POD autoscaling
    enabled: false
    # -- Minimum number of replicas
    minReplicas: 1
    # -- Maximum number of replicas
    maxReplicas: 100
    # -- Target CPU utilization percentage
    targetCPUUtilizationPercentage: 80
    # -- Target Memory utilization percentage
    targetMemoryUtilizationPercentage: 80

  livenessProbe:
    # -- Failure threshold for livenessProbe
    failureThreshold: 6
    # -- Initial delay seconds for livenessProbe
    initialDelaySeconds: 60
    # -- Period seconds for livenessProbe
    periodSeconds: 30
    # -- Success threshold for livenessProbe
    successThreshold: 1
    # -- Timeout in seconds for livenessProbe
    timeoutSeconds: 2

  readinessProbe:
    # -- Failure threshold for readinessProbe
    failureThreshold: 6
    # -- Initial delay seconds for readinessProbe
    initialDelaySeconds: 60
    # -- Period seconds for readinessProbe
    periodSeconds: 30
    # -- Success threshold for readinessProbe
    successThreshold: 1
    # -- Timeout in seconds for readinessProbe
    timeoutSeconds: 2

  # -- Node labels for pod assignment
  nodeSelector: {}

  # -- Toleration labels for pod assignment
  tolerations: []

  # -- Affinity settings for pod assignment
  affinity: {}

  # -- Additional labels to add to the pod
  selectorLabels: {}

  # -- additional environment variables to be added to the frontend pods
  extraEnv: []

# -- additional environment variables to be added to both api and frontend pods
extraEnv: []

# General configuration shared between the frontend and api
config:
  api:
    # @ignored
    filestorage: "gridfs"
    mail:
      # -- Enable sending of emails
      enabled: false
      auth:
        # -- Use existing secret for password details. The secret has to contain the key `mail-password`. When it's set the `config.api.mail.auth.password` is ignored.
        existingSecret: ""
        # -- The password to authenticate to the smtp host when sending emails.
        password: ""
        # -- The username to authenticate to the smtp host when sending emails.
        username: ""
      # -- The email address Countly will send emails from.
      from: ""
      # -- The host of the external SMTP server that Countly should use to send emails.
      host: ""
      # -- The port used to connect to the smtp host.
      port: 0
    # @ignored
    workerCount: "1"
  # @ignored
  nodeOptions: "--max-old-space-size=2048"
  # @ignored
  plugins: "mobile,web,desktop,plugins,density,locale,browser,sources,views,logger,systemlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,times-of-day,compliance-hub,alerts,onboarding,consolidate,remote-config,hooks,dashboards,sdk,data-manager,guides"

ingress:
  # -- Enable ingress record generation
  enabled: false
  # -- IngressClass that will be be used to implement the Ingress
  className: ""
  # -- Additional annotations for the Ingress resource
  annotations: {}
    # cert-manager.io/cluster-issuer: cluster-issuer-name
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- The publicly reachable hostname
  hostname: ""
  # -- Valid values: ImplementationSpecific, Exact, Prefix
  pathType: "Prefix"
  # -- An array with the tls configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

mongodb:
  # -- enable MongoDB™ subchart from Bitnami
  enabled: true
  # -- MongoDB™ architecture. Currently only standalone is supported by this Chart.
  architecture: standalone
  auth:
    # -- Enable authentication
    enabled: false
    # -- Name for a custom database to create
    database: countly
    # @ignored this is only required for the Bitnami MongoDB Subchart
    username: countly

externalMongodb:
  auth:
    # -- Name for a custom database to use
    database: countly
  # -- Hostname of the MongoDB database
  hostname: ""
  # -- Port used to connect to MongoDB database
  port: 27017
