{{- if (ne .Values.kccm.deploymentMode "isolated") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kubevirt-cloud-controller-manager.labels" . | nindent 4 }}
  name: {{ include "kubevirt-cloud-controller-manager.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubevirt-cloud-controller-manager.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubevirt-cloud-controller-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
