---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "kubevirt-cloud-controller-manager.labels" . | nindent 4 }}
  name: {{ include "kubevirt-cloud-controller-manager.fullname" . }}
data:
  cloud-config: |
    loadBalancer:
      creationPollInterval: {{ .Values.kccm.cloudConfig.loadBalancer.creationPollInterval | default 5 }}
      creationPollTimeout: {{ .Values.kccm.cloudConfig.loadBalancer.creationPollTimeout | default 60 }}
    namespace: {{ include "kubevirt-cloud-controller-manager.capi.cluster.namespace" . }}
    {{- if .Values.kccm.cloudConfig.instancesV2.enabled }}
    instancesV2:
      enabled: {{ .Values.kccm.cloudConfig.instancesV2.enabled | default true }}
      zoneAndRegionEnabled: {{ .Values.kccm.cloudConfig.instancesV2.zoneAndRegionEnabled | default false }}
    {{- end }}
