---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "kubevirt-cloud-controller-manager.labels" . | nindent 4 }}
  name: {{ include "kubevirt-cloud-controller-manager.fullname" . }}
rules:
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachineinstances
    verbs:
      - get
      - watch
      - list
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - "*"
  {{- if (ne .Values.kccm.deploymentMode "isolated") }}
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  {{- end }}
