{{- if (and .Values.kccm.cluster.kubeconfig.create (not .Values.kccm.cluster.kubeconfig.existingSecret)) }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "kubevirt-cloud-controller-manager.labels" . | nindent 4 }}
  name: {{ include "kubevirt-cloud-controller-manager.capi.cluster.kubeconfig.secretName" . }}
type: Opaque
data:
  value: {{ include "kubevirt-cloud-controller-manager.capi.cluster.kubeconfig.content" . | b64enc }}
{{- end }}
