{{- if and (not .Values.redis.enabled) (not .Values.externalRedis.auth.existingSecret) (eq (include "kutt.redis.auth.enabled" .) "true") (.Values.externalRedis.auth.password) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kutt.redis.secretName" . }}
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
data:
  {{- include "kutt.redis.userPasswordKey" . | nindent 2 }}: {{ .Values.externalRedis.auth.password | b64enc }}
{{- end }}
