apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "flatcar-linux-update-operator.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "flatcar-linux-update-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
  template:
    metadata:
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "flatcar-linux-update-operator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: agent
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      containers:
        - name: update-agent
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/bin/update-agent"
          env:
          # read by update-agent as the node name to manage reboots for
            - name: UPDATE_AGENT_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /var/run/dbus
              name: var-run-dbus
              readOnly: false
            - mountPath: /etc/flatcar
              name: etc-flatcar
              readOnly: true
            - mountPath: /usr/share/flatcar
              name: usr-share-flatcar
              readOnly: true
            - mountPath: /etc/os-release
              name: etc-os-release
              readOnly: true
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      volumes:
      - name: var-run-dbus
        hostPath:
          path: /var/run/dbus
      - name: etc-flatcar
        hostPath:
          path: /etc/flatcar
      - name: usr-share-flatcar
        hostPath:
          path: /usr/share/flatcar
      - name: etc-os-release
        hostPath:
          path: /etc/os-release
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
