{{- if (and .Values.rbac.create (not .Values.rbac.clusterscoped)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "goldpinger.labels" . | nindent 4 }}
  name: {{ include "goldpinger.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "goldpinger.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "goldpinger.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
