{{- if not .Values.proxy.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "netbird-reverse-proxy.labels" . | nindent 4 }}
  name: {{ include "netbird-reverse-proxy.fullname" . }}
type: Opaque
data:
  token: {{ .Values.proxy.auth.token | b64enc | quote }}
{{- end }}
{{- if and .Values.proxy.crowdsec.apiUrl (not .Values.proxy.crowdsec.auth.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "netbird-reverse-proxy.labels" . | nindent 4 }}
  name: {{ include "netbird-reverse-proxy.proxy.crowdsec.secretName" . }}
type: Opaque
data:
  apiKey: {{ .Values.proxy.crowdsec.auth.apiKey | b64enc | quote }}
{{- end }}
