---
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "netbird-reverse-proxy.labels" . | nindent 4 }}
  name: {{ include "netbird-reverse-proxy.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.service.https.port }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "netbird-reverse-proxy.selectorLabels" . | nindent 4 }}
