{{- if eq .Values.proxy.tls.source "selfSigned" }}
{{- $secretName := include "netbird-reverse-proxy.proxy.tls.secretName" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "netbird-reverse-proxy.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- if $existingSecret }}
  tls.crt: {{ index $existingSecret.data "tls.crt" }}
  tls.key: {{ index $existingSecret.data "tls.key" }}
  {{- else }}
  {{- $cert := genSelfSignedCert .Values.proxy.domain nil (list .Values.proxy.domain) 365 }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  {{- end }}
{{- end }}
