apiVersion: v2
name: standard
description: Gateway API CRDs (standard channel) -- internal subchart of gateway-api-crds, not independently published
type: application
version: 1.1.1
appVersion: "v1.5.1"
