{{- if (not .Values.taiga.common.config.cryptographicSigning.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiga.common.cryptographicSigning.secretName" . }}
data:
  secret-key: {{ .Values.taiga.common.config.cryptographicSigning.secretKey | b64enc }}
{{- end }}
