{{- if .Values.modulesConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "dns-exporter.labels" . | nindent 4 }}
  name: {{ include "dns-exporter.fullname" . }}
data:
  dns_exporter.yml: |
    modules:
      {{- .Values.modulesConfig | toYaml | nindent 6 }}
{{- end }}
